apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
  labels:
    run: nginx1
spec:
  ports:
  - port: 8080
    targetPort: 8170
    nodePort: 32222
    protocol: TCP 
  selector:
    run: nginx1
