apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      containers:
      - name: app1-container
        image: wardviaene/http-echo
        env:
        - name: TEXT
          value: DevOps
        - name: NEXT
          value: "app2:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  selector:
    app: app1
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      containers:
      - name: app2-container
        image: wardviaene/http-echo
        env:
        - name: TEXT
          value: Last
        - name: NEXT
          value: "app3:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
spec:
  selector:
    app: app2
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app3
        version: v1
    spec:
      containers:
      - name: app3-container
        image: wardviaene/http-echo
        env:
        - name: TEXT
          value: Session
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    app: app3
spec:
  selector:
    app: app3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
