apiVersion: v1
kind: Pod
metadata:
  name: nginx.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-pod-demo
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
