apiVersion: v1
kind: Pod
metadata:
  name: nginx.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-pod-demo
    image: mzain/k8s-java-app:1
    ports:
    - name: tomcat-port
      containerPort: 8080
