apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-secrets
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nginx-secret-container
        image: nginx
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: secret-volume
        secret: 
          secretName: secrets
